spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:stock;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: emItc3ByaW5nLWJvb3Qtc3RvY2stcHJvamVjdC10dXRvcmlhbC1qd3Qtc2VjcmV0LWtleQo=

scheduler:
  scrap:
    yahoo: 0 0 0 * * *